version: 2.1

orbs:
  github-maven-deploy: github-maven-deploy/github-maven-deploy@1.0.5
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.11

workflows:
  build-and-test:
    jobs:
      - github-maven-deploy/build-and-test:
          mvn-build-test-command: mvn clean verify -PbuildKar -Dit
          mvn-collect-artifacts-command: |
            mkdir -p ~/project/artifacts/junit/
            cp ~/project/nexus-repository-conan/target/surefire-reports/*.xml ~/project/artifacts/junit/
            cp ~/project/nexus-repository-conan/target/nexus-repository-* ~/project/artifacts/
            cp ~/project/nexus-repository-conan-it/target/failsafe-reports/*.xml ~/project/artifacts/junit/
  run-release:
    jobs:
      - approve-release:
          type: approval
          filters:
            branches:
              only: master
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - approve-release
          ssh-fingerprints: "f3:87:8d:21:0a:df:1e:59:fc:1e:a6:e3:59:f3:35:0f"
          context: rso-base
          mvn-release-prepare-command: mvn --batch-mode release:prepare -DscmCommentPrefix="[skip ci] [maven-release-plugin] " -PbuildKar
          filters:
            branches:
              only: master
